// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate/db) prefers a DIRECT (unpooled) connection when
    // available — migrations use advisory locks that don't work through a
    // connection pooler. The app runtime still uses DATABASE_URL (pooled).
    // Falls back to DATABASE_URL when DIRECT_URL isn't set (e.g. locally).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
